// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "final-project-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// CouponUsecase is an autogenerated mock type for the CouponUsecase type
type CouponUsecase struct {
	mock.Mock
}

// AddCoupon provides a mock function with given fields: username, reqBody
func (_m *CouponUsecase) AddCoupon(username string, reqBody *entity.CouponAddReqBody) (*entity.Coupon, error) {
	ret := _m.Called(username, reqBody)

	var r0 *entity.Coupon
	if rf, ok := ret.Get(0).(func(string, *entity.CouponAddReqBody) *entity.Coupon); ok {
		r0 = rf(username, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Coupon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *entity.CouponAddReqBody) error); ok {
		r1 = rf(username, reqBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddUserCoupon provides a mock function with given fields: userId, couponId
func (_m *CouponUsecase) AddUserCoupon(userId int, couponId int) (*entity.UserCoupon, error) {
	ret := _m.Called(userId, couponId)

	var r0 *entity.UserCoupon
	if rf, ok := ret.Get(0).(func(int, int) *entity.UserCoupon); ok {
		r0 = rf(userId, couponId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserCoupon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userId, couponId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCoupon provides a mock function with given fields: couponId
func (_m *CouponUsecase) DeleteCoupon(couponId int) (*entity.Coupon, error) {
	ret := _m.Called(couponId)

	var r0 *entity.Coupon
	if rf, ok := ret.Get(0).(func(int) *entity.Coupon); ok {
		r0 = rf(couponId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Coupon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(couponId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoupon provides a mock function with given fields:
func (_m *CouponUsecase) GetCoupon() (*[]entity.Coupon, error) {
	ret := _m.Called()

	var r0 *[]entity.Coupon
	if rf, ok := ret.Get(0).(func() *[]entity.Coupon); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Coupon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserCouponByCouponCode provides a mock function with given fields: userId, couponCode
func (_m *CouponUsecase) GetUserCouponByCouponCode(userId int, couponCode string) (*entity.UserCoupon, error) {
	ret := _m.Called(userId, couponCode)

	var r0 *entity.UserCoupon
	if rf, ok := ret.Get(0).(func(int, string) *entity.UserCoupon); ok {
		r0 = rf(userId, couponCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserCoupon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(userId, couponCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserCouponByUsername provides a mock function with given fields: username
func (_m *CouponUsecase) GetUserCouponByUsername(username string) (*[]entity.UserCoupon, error) {
	ret := _m.Called(username)

	var r0 *[]entity.UserCoupon
	if rf, ok := ret.Get(0).(func(string) *[]entity.UserCoupon); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.UserCoupon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCoupon provides a mock function with given fields: username, couponId, reqBody
func (_m *CouponUsecase) UpdateCoupon(username string, couponId int, reqBody *entity.CouponEditReqBody) (*entity.Coupon, error) {
	ret := _m.Called(username, couponId, reqBody)

	var r0 *entity.Coupon
	if rf, ok := ret.Get(0).(func(string, int, *entity.CouponEditReqBody) *entity.Coupon); ok {
		r0 = rf(username, couponId, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Coupon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, *entity.CouponEditReqBody) error); ok {
		r1 = rf(username, couponId, reqBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCouponUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCouponUsecase creates a new instance of CouponUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCouponUsecase(t mockConstructorTestingTNewCouponUsecase) *CouponUsecase {
	mock := &CouponUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
