// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "final-project-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// mediaUpload is an autogenerated mock type for the mediaUpload type
type mediaUpload struct {
	mock.Mock
}

// FileUpload provides a mock function with given fields: username, file
func (_m *mediaUpload) FileUpload(username string, file entity.UserProfileUploadReqBody) (string, error) {
	ret := _m.Called(username, file)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, entity.UserProfileUploadReqBody) string); ok {
		r0 = rf(username, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, entity.UserProfileUploadReqBody) error); ok {
		r1 = rf(username, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMediaUpload interface {
	mock.TestingT
	Cleanup(func())
}

// newMediaUpload creates a new instance of mediaUpload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMediaUpload(t mockConstructorTestingTnewMediaUpload) *mediaUpload {
	mock := &mediaUpload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
